name: Deployment- Reusable Workflow

on:
    workflow_call:
        inputs:
            mongodb-uri:
                required: true
                type: string
            kubectl-version:
                description: provide the required kubectl version
                required: false
                default: v1.26.0
                type: string
            k8s-manifest-dir:
                description: directory containing k8s manifest files
                default: kubernetes/
                required: true
                type: string
            environment:
                description: provide the deployment environment
                default: dev
                required: true
                type: string
        outputs:
            application-url: 
              value: ${{ jobs.reuse-deploy.outputs.APP_INGRESS_URL }}


        secrets:
            k8s-kubeconfig:
                required: true
            mongodb-password:
                required: true

jobs:
    reuse-deploy:
      environment:
        name: ${{ inputs.environment }}
        url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }} 
      outputs:
        APP_INGRESS_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
      runs-on: ubuntu-latest
      steps: 
      - name: checkout repo
        uses: actions/checkout@v4

      - name: k8s kubeconfig
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.k8s-kubeconfig }}

      - name: install kubectl clt
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ inputs.kubectl-version }}

      - name: fetch k8s cluster details
        run: |
          kubectl version 
          echo ----------------
          kubectl get nodes

      - name: save nginx ingress controller ip as a github env variable
        run: |
          echo "INGRESS_IP=$(kubectl -n ingress-nginx get services ingress-nginx-controller -o jsonpath="{.status.loadBalancer.ingress[0].ip}")" >> $GITHUB_ENV

      - name: Replace tokens in manifest files
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["${{ inputs.k8s-manifest-dir }}*.yaml"]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ vars.DOCKERHUB_USERNAME}}/solar-system:${{ github.sha }}
          INGRESS_IP: ${{ env.INGRESS_IP }}

      - name: check files
        run: |
          cat ${{ inputs.k8s-manifest-dir }}*.yaml

      - name: create mongodb secret
        run: |
          kubectl -n ${{ vars.NAMESPACE }} create secret generic mongo-db-creds \
          --from-literal=MONGO_URI=${{ inputs.mongodb-uri }} \
          --from-literal=MONGO_USERNAME=${{ vars.MONGO_USERNAME }} \
          --from-literal=MONGO_PASSWORD=${{ secrets.mongodb-password }} \
          --save-config \
          --dry-run=client \
          -o yaml | kubectl apply -f -

      - name: deploy to dev env
        run: |
          kubectl apply -f ${{ inputs.k8s-manifest-dir }}

      - name: set app ingress host url
        id: set-ingress-host-address
        run: | 
         echo "APP_INGRESS_HOST=$(kubectl -n ${{ vars.NAMESPACE }} get ingress -o jsonpath="{{.items[0].spec.tls[0].hosts[0]}}")" >> "$GITHUB_OUTPUT"
  
